# Generated by Django 6.0 on 2026-02-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование услуги')),
                ('count', models.BooleanField(blank=True, max_length=10, null=True, verbose_name='Стоимость')),
            ],
        ),
    ]
