# Generated by Django 6.0 on 2026-02-26 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kopykop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricelist',
            options={'ordering': ('name',), 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
    ]
