# Generated by Django 6.0 on 2026-02-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kopykop', '0002_alter_pricelist_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='count',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Стоимость'),
        ),
    ]
