# Generated by Django 6.0 on 2026-02-26 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kopykop', '0003_alter_pricelist_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricelist',
            options={'ordering': ('-id',), 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
    ]
