# Generated by Django 6.0 on 2026-02-26 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kopykop', '0004_alter_pricelist_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricelist',
            options={'ordering': ('id',), 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
    ]
