# Generated by Django 6.0 on 2026-02-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kopykop', '0005_alter_pricelist_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок новости')),
                ('title_big', models.CharField(blank=True, max_length=100, null=True, verbose_name='Важная новость')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Описание новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ('id',),
            },
        ),
    ]
