# Generated by Django 6.0 on 2026-02-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kopykop', '0006_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
