# Generated by Django 6.0 on 2026-02-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kopykop', '0007_news_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='images_description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание услуги'),
        ),
        migrations.AddField(
            model_name='news',
            name='images_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст услуги (средний)'),
        ),
        migrations.AddField(
            model_name='news',
            name='images_title_big',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст услуги (большой)'),
        ),
    ]
