# Generated by Django 6.0 on 2026-03-02 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kopykop', '0008_news_images_description_news_images_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders_name', models.CharField(blank=None, max_length=100, null=None, verbose_name='Название заказа')),
                ('number', models.CharField(blank=None, max_length=15, null=None, verbose_name='Номер телефона')),
                ('fio', models.CharField(blank=None, max_length=100, null=None, verbose_name='Ф.И')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='kopykop.pricelist')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('id',),
            },
        ),
    ]
