# Generated by Django 6.0 on 2026-03-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kopykop', '0009_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='fio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ф.И'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orders_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название заказа'),
        ),
    ]
