# Generated by Django 6.0 on 2026-03-19 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kopykop', '0010_alter_orders_fio_alter_orders_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='description',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_big',
        ),
    ]
