# Generated by Django 6.0 on 2026-03-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kopykop', '0014_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/%d/', verbose_name='Аватарка'),
        ),
    ]
