# Generated by Django 6.0 on 2026-03-21 11:05

import kopykop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kopykop', '0015_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AddField(
            model_name='orders',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=kopykop.models.order_file_path, verbose_name='Файл'),
        ),
    ]
